version: '3'
services:
  murko-server:
    container_name: murko-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8008:8008
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /Users/smith_k/code/murko/examples:/Users/smith_k/code/murko/examples # testing..
    networks:
      - my-network

networks:
  my-network: