version: '3'
services:
  murko-server:
    container_name: murko-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8008:8008
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #add your site specific filepath mount here
    networks:
      - my-network

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - my-network

networks:
  my-network: